?start: program

program: statement*

?statement: variable_declaration
          | variable_assignment
          | this_assignment
          | function_declaration
          | type_declaration
          | class_declaration
          | interface_declaration
          | if_statement
          | for_statement
          | while_statement
          | try_statement
          | match_statement
          | return_statement
          | throw_statement
          | expression_statement
          | spawn_statement
          | import_statement

// Module System
import_statement: "import" dotted_name

dotted_name: IDENTIFIER ("." IDENTIFIER)*

// Variable Declaration
variable_declaration: "DEF" IDENTIFIER type "=" expression
variable_assignment: IDENTIFIER ":=" expression
this_assignment: "THIS" ":" IDENTIFIER ":=" expression

// Function Declaration
function_declaration: "FUNC" (IDENTIFIER | qualified_identifier) "(" parameter_list? ")" type function_body "END" "FUNC"
qualified_identifier: IDENTIFIER (":" IDENTIFIER)*
parameter_list: parameter ("," parameter)*
parameter: IDENTIFIER type
function_body: statement*

// Type Declaration
type_declaration: "TYPE" IDENTIFIER type_body "END" "TYPE"
              | "TYPE" IDENTIFIER extends_clause type_body "END" "TYPE"

type_body: type_field*
type_field: IDENTIFIER type

// Class Declaration  
class_declaration: "CLASS" IDENTIFIER extends_clause? implements_clause? class_body "END" "CLASS"
extends_clause: "EXTENDS" IDENTIFIER ("," IDENTIFIER)
implements_clause: "IMPLEMENTS" IDENTIFIER ("," IDENTIFIER)



class_body: class_member*
class_member: access_modifier? STATIC? OVERRIDE? (property_declaration | method_declaration)
            | constructor_declaration

access_modifier: PUBLIC | PRIVATE | PROTECTED

property_declaration: IDENTIFIER type ("=" expression)?

method_declaration: "FUNC" IDENTIFIER "(" parameter_list? ")" type function_body "END" "FUNC"

constructor_declaration: "CONSTRUCTOR" "(" parameter_list? ")" function_body "END" "CONSTRUCTOR"

// Interface Declaration
interface_declaration: "INTERFACE" IDENTIFIER interface_body "END" "INTERFACE"
interface_body: interface_member*
interface_member: "FUNC" IDENTIFIER "(" parameter_list? ")" type

// Control Flow
if_statement: "if" "$" expression "$" "do" statement* elif_clause* else_clause? "END" "if"
elif_clause: "else" "if" "$" expression "$" "do" statement*
else_clause: "else" "do" statement*

for_statement: "for" "DEF" IDENTIFIER type "in" expression "do" statement* "END" "for"

while_statement: "while" "$" expression "$" "do" statement* "END" "while"

// Error Handling
try_statement: "TRY" statement* catch_clause* finally_clause? "END" "TRY"
catch_clause: "CATCH" IDENTIFIER type "do" statement*
finally_clause: "FINALLY" statement*

// Pattern Matching
match_statement: "MATCH" expression case_clause* default_clause? "END" "MATCH"
case_clause: "CASE" pattern guard? "do" statement*
default_clause: "DEFAULT" "do" statement*
pattern: literal
       | IDENTIFIER
       | type IDENTIFIER
       | "[" pattern_list? "]"
       | object_literal
       | map_literal
       | tuple_literal
guard: "IF" "$" expression "$"
pattern_list: pattern ("," pattern)*

// Statements
return_statement: "RETURN" expression?
throw_statement: "THROW" expression
expression_statement: expression
spawn_statement: "SPAWN" expression

// Expressions
?expression: or_expression

?or_expression: and_expression
              | or_expression OR and_expression

?and_expression: equality_expression  
               | and_expression AND equality_expression

?equality_expression: relational_expression
                    | equality_expression equality_op relational_expression

equality_op: EQUAL_TO | NOT_EQUAL_TO

?relational_expression: additive_expression
                     | relational_expression relational_op additive_expression

relational_op: LESS_THAN | GREATER_THAN | LESS_THAN_OR_EQUAL_TO | GREATER_THAN_OR_EQUAL_TO

?additive_expression: multiplicative_expression
                   | additive_expression PLUS multiplicative_expression
                   | additive_expression MINUS multiplicative_expression

?multiplicative_expression: unary_expression
                         | multiplicative_expression TIMES unary_expression
                         | multiplicative_expression DIVIDE unary_expression
                         | multiplicative_expression MODULO unary_expression

?unary_expression: postfix_expression
                | NOT unary_expression
                | MINUS unary_expression
                | PLUS unary_expression

?postfix_expression: primary_expression
                  | postfix_expression method_call
                  | postfix_expression property_access
                  | postfix_expression array_access

method_call: ":" method_name ":" "(" argument_list? ")"
          | ":" method_name ":"

method_name:  IDENTIFIER

property_access: "." IDENTIFIER

array_access: "[" expression "]"

?primary_expression: literal
                  | IDENTIFIER
                  | IDENTIFIER "(" argument_list? ")"
                  | "(" expression ")"
                  | array_literal
                  | empty_object_literal
                  | tuple_literal
                  | object_literal
                  | map_literal
                  | lambda_expression
                  | anonymous_function
                  | "THIS"
                  | "SUPER" "(" argument_list? ")"

// Literals
literal: BOOLEAN | INTEGER | FLOAT | STRING | CHAR 

array_literal: "[" argument_list? "]"


map_literal: "{" map_entries+ "}"
map_entries: map_entry ("," map_entry)*
map_entry: expression "->" expression 
empty_object_literal: "{" "}"
object_literal: "{" dict_entries+ "}" 

dict_entries: dict_entry ("," dict_entry)*
dict_entry: IDENTIFIER ":" expression                    // object entry (property: value)

tuple_literal: "(" expression "," expression ("," expression)* ")"

lambda_expression: "FUNC" "(" parameter_list? ")" "->" expression
anonymous_function: "FUNC" "(" parameter_list? ")" function_body "END" "FUNC"

argument_list: expression ("," expression)*

// Types
type: primitive_type
    | array_type  
    | map_type
    | tuple_type
    | custom_type

primitive_type: INT_TYPE | FLOAT_TYPE | BOOL_TYPE | CHAR_TYPE | STR_TYPE | VOID_TYPE | ANY_TYPE

array_type: "#[" type "]"

map_type: "#{" type "," type "}"

tuple_type: "#(" type ("," type)+ ")"

custom_type: "#" IDENTIFIER

// Tokens
IDENTIFIER: /[a-zA-Z_][a-zA-Z0-9_]*/

INTEGER: /[0-9]+/

FLOAT: /[0-9]+\.[0-9]+/

STRING: /"([^"\\]|\\.)*"/

CHAR: /'([^'\\]|\\.)'/

BOOLEAN: TRUE | FALSE

// Comments and Whitespace
COMMENT: "//" /[^\n]*/

// TYPE DEFINITIONS

INT_TYPE: "#int"
FLOAT_TYPE: "#float"
BOOL_TYPE: "#bool"
CHAR_TYPE: "#char"
STR_TYPE: "#str"
VOID_TYPE: "#void"
ANY_TYPE: "#any"

// BOOL_TYPE
TRUE: ":T:"
FALSE: ":F:"

// RELATIONAL OPERATORS
GREATER_THAN: ">"
LESS_THAN: "<"
GREATER_THAN_OR_EQUAL_TO: ">="
LESS_THAN_OR_EQUAL_TO: "<="

// EQUALITY OPERATORS
EQUAL_TO: "=="
NOT_EQUAL_TO: "!="

// ACCESS MODIFIERS
PUBLIC: "PUBLIC"
PRIVATE: "PRIVATE"
PROTECTED: "PROTECTED"

// STATIC
STATIC: "STATIC"

// OVERRIDE
OVERRIDE: "OVERRIDE"

PLUS: "+"
MINUS: "-"
TIMES: "*"
DIVIDE: "/"
MODULO: "%"
NOT: "!"
AND: "&&"
OR: "||"


%import common.WS
%ignore WS
%ignore COMMENT
