import os

from lark import Lark

from src.transformer import SugarTransformer

# Construct the absolute path to the grammar file
GRAMMAR_FILE = os.path.join(os.path.dirname(__file__), "sugar_grammar.lark")


def get_parser():
    """Creates and returns a Lark parser for the Sugar language."""
    with open(GRAMMAR_FILE, "r", encoding="utf-8") as f:
        grammar = f.read()
    return Lark(
        grammar,
        start="program",
        parser="lalr",
        transformer=SugarTransformer(),
    )


def parse_to_ast(code: str):
    """Parses Sugar code and returns the AST."""
    parser = get_parser()
    try:
        parser.lex(code)

    except Exception as e:
        raise RuntimeError(f"Error during lexing: {e}")
    # print(code)
    # print("\n--- Lexer Output (Tokens) ---")
    # try:
    #     # Iterate over tokens generated by the lexer
    #     tokens = list(parser.lex(code))
    #     for token in tokens:
    #         print(
    #             f"Type: {token.type:<20} Value: '{token.value:<25}' Line: {token.line:<3} Col: {token.column}"
    #         )
    # except Exception as e:
    #     print(f"Error during lexing: {e}")
    # print("--- End Lexer Output ---\n")
    return parser.parse(code)
